name: Terraform Pull Request Report Generator
description: Updates Pull Requests with visual diff of Terraform Plan changes

branding:
  color: red
  icon: search

inputs:
  github-token:
    description: The GitHub token used to post comments on pull requests
    default: ${{ github.token }}

  terraform-text:
    description: path to Terraform Plan text output file
    required: true

  terraform-json:
    description: path to Terraform Plan JSON output file
    required: true

runs:
  using: docker
  image: docker://ahmadnassri/action-terraform-report:v2
